src/books/urls.py
from django.contrib import admin
from django.urls import path
from books import views 

urlpatterns = [
    path('', views.homeView, name='home'),
    path('category/<slug:slug>', views.categoryView, name='category'),
    path('book/<str:slug>/', views.bookDetail, name='book_detail'),
    path('book/<str:slug>/submit_rating/', views.submitRating, name='submit_rating'),
    path('cart/', views.cart_view, name='cart'),
    path('cart/add/<str:slug>/', views.add_to_cart, name='add_to_cart'),
    path('cart/remove/<int:item_id>/', views.remove_from_cart, name='remove_from_cart'),
    path('cart/update/<int:item_id>/', views.update_cart, name='update_cart'),
    path('cart/checkout', views.checkoutView, name='checkout'),
    path('placeorder/', views.place_order, name='order'),
    path('add_address/', views.add_shipping_address, name='add_shipping_address'),
    path('set_default_address/<int:address_id>/', views.set_default_address, name='set_default_address'),
    path('order_history/', views.order_history, name='order_history'),

]

src/bookstore/urls.py
from django.urls import path
from .views import BookList, BookDetail, generate_api_token, generate_token_page

app_name = 'bookstore' 

urlpatterns = [
    path('generate-token-page/', generate_token_page, name='generate_token_page'),
    path('generate-api-token/', generate_api_token, name='generate_api_token'),
    path('books/', BookList.as_view(), name='book-list'),
    path('books/<int:pk>/', BookDetail.as_view(), name='book-detail'),
]

# api call for the user root
# curl -H "Authorization: Token a7cdb0fd1a4664b9d744e4b51a70146586f55a5b" http://localhost:8000/api/v1/books/{23}/

src/storyKeeper/urls.py
from django.contrib import admin
from django.urls import path, include
## from rest_framework.schemas import get_schema_view # for the open api documention and url 
from drf_yasg import openapi
from drf_yasg.views import get_schema_view 
from rest_framework import permissions
from django.conf import settings
from django.conf.urls.static import static

# for open api schema
schema_view = get_schema_view(
    openapi.Info(
        title="StoryKeeper API",
        default_version='v1',
        description="Find your Story",
        terms_of_service="https://www.google.com/policies/terms/",
        contact=openapi.Contact(email="raman.c@applify.co"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('books.urls')),
    path('accounts/', include('members.urls')),
    path("accounts/", include("django.contrib.auth.urls")),
    path('accounts/', include('allauth.urls')),
    path('api/v1/', include('bookstore.urls')),
    path('api/v1/', include('userData.urls')),
    path('api/auth/', include('rest_framework.urls')),
    path('api/v1/dj-rest-auth/', include('dj_rest_auth.urls')),
    path('api/v1/dj-rest-auth/registration/',include('dj_rest_auth.registration.urls')),
    path('swagger<format>/', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    path('swagger/', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    path('redoc/', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),
]  
urlpatterns = urlpatterns + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
# for the openapi Schema >>>>>>>>>>>>>>>>>>>>>>>>>>
    # path('openapi', get_schema_view( # new
    #     title="Blog API",
    #     description="A sample API for learning DRF",
    #     version="1.0.0"
    # ), name='openapi-schema'),

src/bookstore/models.py
from django.db import models

# Create your models here.

src/bookstore/views.py
from rest_framework import generics
from books.models import Book
from .serializers import BookSerializer
from django.contrib.auth.decorators import login_required
from rest_framework.authtoken.models import Token
from django.http import JsonResponse
from django.shortcuts import render
from rest_framework.permissions import IsAuthenticated


@login_required
def generate_api_token(request):
    user = request.user
    token, created = Token.objects.get_or_create(user=user)
    return JsonResponse({'token': token.key})

@login_required
def generate_token_page(request):
    return render(request, 'api_page.html')

class BookList(generics.ListCreateAPIView):
    queryset = Book.objects.all()
    serializer_class = BookSerializer 

class BookDetail(generics.RetrieveUpdateDestroyAPIView):
    queryset = Book.objects.all()
    serializer_class = BookSerializer

src/bookstore/templates/api_page.html
{% extends 'base.html' %}

{% block title %}StoryKeeper API{% endblock %}

{% block content %}

{% load static %}

{% load crispy_forms_tags %}

<div>
    <button class="mt-3 justify-content-center" id="generateTokenButton">Generate API Token</button>
    <button class="mt-3 justify-content-center" id="copyTokenButton" style="display: none;">Copy Token</button>
</div>

<div>
    <code id="tokenDisplay" style="display: none;"></code>
</div>
<br>
<hr>
<br>
<div>
    <a class="text-success" id="accessApiButton" href="#" target="_blank">Access Browsable API</a>
</div>


<script>
$(document).ready(function() {
    $('#generateTokenButton').click(function() {
        $.ajax({
            url: '{% url "bookstore:generate_api_token" %}',  <!-- Updated URL name -->
            method: 'GET',
            xhrFields: {
                withCredentials: true
            },
            success: function(response) {
                // Display the token
                $('#tokenDisplay').text(response.token).show();
                $('#copyTokenButton').show();
            },
            error: function(error) {
                alert('Error: Unable to generate token');
            }
        });
    });

    $('#copyTokenButton').click(function() {
        // Copy token to clipboard
        var tokenText = $('#tokenDisplay').text();
        var textarea = document.createElement('textarea');
        textarea.value = tokenText;
        document.body.appendChild(textarea);
        textarea.select();
        document.execCommand('copy');
        document.body.removeChild(textarea);

        // You can provide feedback to the user that the token is copied if needed
        alert('Token copied to clipboard: ' + tokenText);
    });
});
</script>
    

{% endblock %}